name: financeflow_pro
description: A comprehensive financial management and banking application with advanced transaction tracking, drag-and-drop kanban boards, and professional UI/UX design.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & Design
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  lottie: ^2.7.0
  shimmer: ^3.0.0
  cached_network_image: ^3.3.0

  # State Management
  provider: ^6.1.1

  # Navigation & Routing
  go_router: ^12.1.3

  # Local Storage & Database
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  sqflite: ^2.3.0
  path: ^1.8.3

  # Network & API
  dio: ^5.4.0
  http: ^1.1.0
  connectivity_plus: ^5.0.2

  # Authentication & Security
  local_auth: ^2.1.7
  crypto: ^3.0.3
  flutter_secure_storage: ^9.0.0

  # Utils & Helpers
  intl: ^0.19.0
  uuid: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10
  package_info_plus: ^4.2.0
  device_info_plus: ^9.1.2

  # Charts & Analytics
  fl_chart: ^0.65.0

  # Image & File Handling
  file_selector: ^1.0.3 # Replaced file_picker with file_selector
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  permission_handler: ^11.0.1

  # QR Code & Barcode
  qr_flutter: ^4.1.0

  # Animations
  animated_text_kit: ^4.2.2

  # Hardware
  vibration: ^1.8.4

  # Development Tools
  logger: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Quality
  flutter_lints: ^2.0.3

  # Build Tools
  build_runner: ^2.4.8
  hive_generator: ^2.0.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1

  # Testing
  mockito: ^5.4.4
  integration_test:
    sdk: flutter

# Flutter configuration
flutter:
  uses-material-design: true

  # App Assets
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/data/
    - assets/fonts/
    - assets/logo/

  # Custom Fonts
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

# Flutter Launcher Icons Configuration
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/app_icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/logo/app_icon.png"
    background_color: "#2563EB"
    theme_color: "#2563EB"
  windows:
    generate: true
    image_path: "assets/logo/app_icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/logo/app_icon.png"

# Flutter Native Splash Configuration
flutter_native_splash:
  color: "#2563EB"
  image: assets/logo/splash_logo.png
  color_dark: "#1E293B"
  image_dark: assets/logo/splash_logo_dark.png
  android_12:
    image: assets/logo/android12_splash.png
    icon_background_color: "#2563EB"
    image_dark: assets/logo/android12_splash_dark.png
    icon_background_color_dark: "#1E293B"
  web: false

# Dependency Override (if needed)
dependency_overrides:
# Add any dependency overrides here if needed